server:
  port: 8080

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/task_manager_db # for local testing
    url: jdbc:postgresql://taskmanager-db:5432/task_manager_db # for docker-compose
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

holidays:
  api:
    url: https://date.nager.at/api/v3/PublicHolidays

