version: '3.8'

services:
  db:
    build:
      context: ./task-manager-db
    container_name: task-manager-db
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasknet

  backend:
    build:
      context: ./task-manager-be
    container_name: task-manager-be
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - tasknet

  frontend:
    build:
      context: ./task-manager-ui
      dockerfile: Dockerfile
    container_name: task-manager-ui
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - tasknet

volumes:
  pgdata:


networks:
  tasknet:
