server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

